project:
  type: website

website:
  title: "GG Blog"
  page-navigation: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
format:
  html:
    theme: light
    css: styles.css
    toc: true
    smooth-scroll: true
